language: objective-c
os: osx
osx_image: xcode7.3
before_install:
  gem install xcpretty -N --no-ri --no-rdoc
script:
- |
  set -o pipefail
  xcodebuild build -workspace imbk.xcworkspace -sdk iphonesimulator -scheme imbk -configuration Debug | xcpretty -c
