fastlane_version "1.47.0"

default_platform :ios

skip_docs

platform :ios do
    lane :clean do
        keychain_name = "imbk-certs.keychain"

        delete_keychain(
            name: keychain_name
        )
    end

    lane :register_devices do
        register_devices(
            devices_file: 'fastlane/devices.txt'
        )
    end

    lane :beta do
        keychain_name = "imbk-certs.keychain"

        cocoapods()

        swiftlint(
            mode: :lint,
            config_file: '.swiftlint.yml',
            ignore_exit_status: false
        )

        create_keychain(
            name: keychain_name,
            default_keychain: false,
            unlock: true,
            timeout: 3600,
            password: SecureRandom.base64
        )

        # Import distribution certificate
        sh "security import Certificates/distribution.p12 -k ~/Library/Keychains/" + keychain_name + " -P $KEY_PASSWORD -T /usr/bin/codesign -T /usr/bin/security"
        sh "security import Certificates/distribution.cer -k ~/Library/Keychains/" + keychain_name + " -T /usr/bin/codesign -T /usr/bin/security"

        increment_build_number(build_number: number_of_commits)

        # Build
        gym(
            configuration: "Ad Hoc",
            sdk: "iphoneos9.3",
            clean: true,
            use_legacy_build_api: true,
            export_method: "enterprise",
            scheme: "imbk",
            codesigning_identity: "iPhone Distribution: Andrew Ferrier (BPR9292AKL)",
            provisioning_profile_path: "fastlane/Certificates/imbkDistribution.mobileprovision"
        )

        # Push to Hockey
        hockey(
            api_token: ENV["HOCKEY_API_TOKEN"],
            public_identifier: ENV["HOCKEY_APP_ID"],
            notify: '0',
            status: '2',
            notes: last_git_commit[:message] + "n(Uploaded automatically via fastlane)"
        )

        delete_keychain(
            name: keychain_name
        )
    end
end
